DataConfig:
  dataset_id: 144  # UCI ML Repo ID
  test_size: 0.2
  random_state: 21
  
  ordinal_features:
    - checking_status
    - credit_history
    - savings
    - employment
    - job
  
  nominal_features:
    - purpose
    - personal_status_sex
    - other_debtors
    - property
    - other_installment
    - housing
    - telephone
    - foreign_worker
  
  num_features:
    - duration
    - credit_amount
    - installment_rate
    - residence_since
    - age
    - existing_credits
    - people_liable
    - credit_per_existing
    - credit_per_age
    - credit_per_duration

# Model Configurations
model:

  # Logistic Regression
  logreg:
    penalty: "l2"
    C: 0.0001
    solver: "liblinear"
    max_iter: 2000
    use_smote: true  # Toggle this for experiments!
    class_weight: null
    
    # GridSearch
    cv_folds: 5
    scoring: "recall"
    param_grid:
      clf__penalty: ["l1", "l2"]
      clf__C: [0.0001, 0.001, 0.01, 0.1, 1.0]
      clf__solver: ["liblinear"]
      clf__max_iter: [1000, 2000, 3000]
  
  # XGBoost
  xgboost:
    n_estimators: 500
    max_depth: 5
    learning_rate: 0.01
    subsample: 0.7
    colsample_bytree: 0.9
    reg_lambda: 10
    reg_alpha: 0.5
    gamma: 0
    scale_pos_weight: 2.33  # Add this! (ratio of Good/Bad classes ~700/300)
    min_child_weight: 1     # Add this - lower allows more aggressive splits
    
    # GridSearch
    cv_folds: 5
    scoring: "recall"
    param_grid:
      clf__n_estimators: [300, 500, 1000]
      clf__max_depth: [3, 5]
      clf__learning_rate: [0.001, 0.01, 0.1]
      clf__subsample: [0.6, 0.9]
      clf__colsample_bytree: [0.7, 1.0]
      clf__reg_lambda: [0, 1, 5]
      clf__reg_alpha: [0, 0.5, 1.0]
      clf__gamma: [0, 0.5, 1.0]
      clf__scale_pos_weight: [2, 2.33, 3]  # Test different weights
      clf__min_child_weight: [1, 3, 5]  # Add this

WandB:
  project_name: "QuantitativeRiskManagement"
  entity: "jojs-it-universitetet-i-k-benhavn"
  API_key: ${api_key}